[package]
name = "imageoptimize"
version = "0.1.5"
edition = "2021"
authors = ["Tree Xie <tree.xie@outlook.com>"]
categories = ["multimedia::images"]
keywords = ["image", "optimize"]
description = "Optimize image of multi format"
license = "Apache-2.0"
homepage = "https://github.com/vicanso/imageoptimize"
repository = "https://github.com/vicanso/imageoptimize"
exclude = [
    "assets/*",
    "test/*",
    "Cargo.lock"
]
readme = "./README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.81"
avif-decode = "1.0.1"
base64 = "0.22.1"
dssim = "3.3.2"
image = { version = "0.25.2", features = ["webp", "avif"] }
imagequant = { version = "4.3.3", default-features = false }
lodepng = "3.10.5"
mozjpeg = "0.10.9"
reqwest = "0.12.7"
rgb = "0.8.50"
snafu = "0.8.4"
substring = "1.4.5"
urlencoding = "2.1.3"

[dev-dependencies]
pretty_assertions = "1.4.0"
tokio-test = "0.4.4"
