[package]
name = "imageoptimize"
version = "0.1.3"
edition = "2021"
authors = ["Tree Xie <tree.xie@outlook.com>"]
categories = ["multimedia::images"]
keywords = ["image", "optimize"]
description = "Optimize image of multi format"
license = "Apache-2.0"
homepage = "https://github.com/vicanso/imageoptimize"
repository = "https://github.com/vicanso/imageoptimize"
exclude = [
    "assets/*",
    "test/*",
    "Cargo.lock"
]
readme = "./README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.77"
avif-decode = "1.0.0"
base64 = "0.22.0"
dssim = "3.3.1"
image = { version = "0.24.8", features = ["webp-encoder", "avif-encoder"] }
imagequant = { version = "4.3.0", default-features = false }
lodepng = "3.10.1"
mozjpeg = "0.10.7"
reqwest = "0.11.24"
rgb = "0.8.37"
snafu = "0.8.1"
substring = "1.4.5"
urlencoding = "2.1.3"

[dev-dependencies]
pretty_assertions = "1.4.0"
tokio-test = "0.4.3"
